# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectDirBtn = QtWidgets.QToolButton(self.centralwidget)
        self.selectDirBtn.setMinimumSize(QtCore.QSize(100, 70))
        self.selectDirBtn.setObjectName("selectDirBtn")
        self.horizontalLayout.addWidget(self.selectDirBtn)
        self.scanFeatureBtn = QtWidgets.QToolButton(self.centralwidget)
        self.scanFeatureBtn.setMinimumSize(QtCore.QSize(100, 70))
        self.scanFeatureBtn.setObjectName("scanFeatureBtn")
        self.horizontalLayout.addWidget(self.scanFeatureBtn)
        self.scanAgeBtn = QtWidgets.QToolButton(self.centralwidget)
        self.scanAgeBtn.setMinimumSize(QtCore.QSize(100, 70))
        self.scanAgeBtn.setObjectName("scanAgeBtn")
        self.horizontalLayout.addWidget(self.scanAgeBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photographer Assistant"))
        self.selectDirBtn.setText(_translate("MainWindow", "Select Directory"))
        self.scanFeatureBtn.setText(_translate("MainWindow", "Scan Feature"))
        self.scanAgeBtn.setText(_translate("MainWindow", "Scan Age"))
